#!/usr/bin/env/ bash

# running apache2 on the 265-0 docker-container
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common

# key
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker.io
docker run --rm -it -p 9020:8080 -p 9021:5900 $(whoami)

# Optionally --> 
#									sudo docker search <image_name e.g kali / ubuntu / linux>
#									sudo docker run -it kalilinux/kali-rolling
sudo systemctl start docker
sudo systemctl enable docker
# EOF
