#!/usr/bin/env bash

#  Requirements:

#    Name of the created private key must be school
 #   Number of bits in the created key to be created 4096
  #  The created key must be protected by the passphrase betty
  
ssh-keygen -t rsa -b 4096 -C "ubuntu@web-01" -f school -N "betty" 
